
trigger:
- "*"

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: 'BlazorApp3/*.csproj'
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'BlazorApp3/*.csproj'
      arguments: '--output BlazorApp3Build'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'ls BlazorApp3Build'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration $(BuildConfiguration) --output BlazorApp3Publish'
      workingDirectory: '$(System.DefaultWorkingDirectory)/BlazorApp3Build'
      zipAfterPublish: True
  
  

