
trigger:
- "*"

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: 'BlazorApp3/*.csproj'
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'BlazorApp3/*.csproj'
      # arguments: '--output BlazorApp3Build'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      # script: 'cd BlazorApp3Build'
  # - task: DotNetCoreCLI@2
  #   inputs:
  #     command: 'publish'
  #     publishWebProjects: false
  #     arguments: '--output BlazorApp3Publish'
  #     workingDirectory: '$(System.DefaultWorkingDirectory)/BlazorApp3'
  #     zipAfterPublish: True
  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      publishWebProjects: false
      
      arguments: '--output $(Build.ArtifactStagingDirectory) --self-contained false'
      workingDirectory: '$(System.DefaultWorkingDirectory)/BlazorApp3'
      zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'BlazorApp3'

  

