stages:
- stage: build
  jobs:
  - job: job1
    strategy: 
      parallel: 4
    steps:
    - script: echo Zenman on board
- stage: copy
  jobs:
    - job: copy
      steps:
        - script: echo copying files
- stage: Deploy
  jobs:
    - job: deploy
      steps:
        - script: echo deploying
